---
- name: Deploy HTML page # Выполнять всё будем на хостах группы ec2_servers с правами суперпользователя (root), также отключаем автоматический сбор фактов
  hosts: ec2_servers
  become: true
  gather_facts: false

  tasks:
    - name: Copy index.html to web server directory # Копироуем index.html из директории на сервере в директорию на хосте
      copy:
        src: /home/mikhailomk/ans/index.html
        dest: /var/www/html/index.html

    - name: Ensure Nginx service is restarted # Перезапускаем nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

# После запуска плейбука можно будет в вашем браузере перейти по следующей ссылке <your_ipv4_address>
