---
- name: Install and start Nginx # Выполнять всё будем на хостах группы ec2_servers с правами суперпользователя (root)
  hosts: ec2_servers
  become: true

  tasks:
    - name: Update apt package cache # Обновляем пакеты
      apt:
        update_cache: yes

    - name: Install Nginx package # Устанавливаем последнюю версию nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure Nginx service is enabled and running # Запускаем nginx 
      systemd:
        name: nginx
        state: started
        enabled: yes
